In [1]:
import pandas as pd
import pandapower as pp
import numpy as np

In [6]:
data_file = "Final_Training_Data_15k.csv"

# Load the raw dataset
try:
    df = pd.read_csv(data_file)
    print(f"Data loaded successfully. Rows: {len(df)}, Columns: {len(df.columns)}")
except Exception as e:
    print(f"Error loading file: {e}")

Data loaded successfully. Rows: 15001, Columns: 60

In [7]:
df.columns

Index(['P100', 'P101', 'P102', 'P103', 'P104', 'P105', 'P106', 'P107', 'P108',
       'P109', 'P110', 'P111', 'P112', 'Q100', 'Q101', 'Q102', 'Q103', 'Q104',
       'Q105', 'Q106', 'Q107', 'Q108', 'Q109', 'Q110', 'Q111', 'Q112',
       'P_flow_99_100', 'Q_flow_99_100', 'P_flow_100_101', 'Q_flow_100_101',
       'P_flow_99_102', 'Q_flow_99_102', 'P_flow_99_103', 'Q_flow_99_103',
       'P_flow_102_103', 'Q_flow_102_103', 'P_flow_102_104', 'Q_flow_102_104',
       'P_flow_99_105', 'Q_flow_99_105', 'P_flow_103_104', 'Q_flow_103_104',
       'P_flow_104_105', 'Q_flow_104_105', 'P_flow_104_106', 'Q_flow_104_106',
       'P_flow_104_107', 'Q_flow_104_107', 'P_flow_105_106', 'Q_flow_105_106',
       'P_flow_107_108', 'Q_flow_107_108', 'P_flow_102_109', 'Q_flow_102_109',
       'P_flow_108_109', 'Q_flow_108_109', 'P_flow_109_110', 'Q_flow_109_110',
       'P_flow_109_111', 'Q_flow_109_111'],
      dtype='object')

In [8]:
df = df.loc[:, (df != 0).any(axis=0)]

In [9]:
df.columns

Index(['P100', 'P101', 'P102', 'P103', 'P104', 'P105', 'P106', 'P107', 'P108',
       'P109', 'P111', 'P112', 'Q100', 'Q102', 'Q103', 'Q104', 'Q105', 'Q106',
       'Q107', 'Q108', 'Q109', 'Q111', 'P_flow_99_100', 'Q_flow_99_100',
       'P_flow_100_101', 'Q_flow_100_101', 'P_flow_99_102', 'Q_flow_99_102',
       'P_flow_99_103', 'Q_flow_99_103', 'P_flow_102_103', 'Q_flow_102_103',
       'P_flow_102_104', 'Q_flow_102_104', 'P_flow_99_105', 'Q_flow_99_105',
       'P_flow_103_104', 'Q_flow_103_104', 'P_flow_104_105', 'Q_flow_104_105',
       'P_flow_104_106', 'Q_flow_104_106', 'P_flow_104_107', 'Q_flow_104_107',
       'P_flow_105_106', 'Q_flow_105_106', 'P_flow_107_108', 'Q_flow_107_108',
       'P_flow_102_109', 'Q_flow_102_109', 'P_flow_108_109', 'Q_flow_108_109',
       'P_flow_109_110', 'Q_flow_109_110', 'P_flow_109_111', 'Q_flow_109_111'],
      dtype='object')

In [10]:
df.shape[1]

56

In [11]:
from sklearn.model_selection import train_test_split

# Split your dataset
train_df = df.iloc[:10000]   # first 10k for training
test_df  = df.iloc[10000:]   # rest for testing

In [13]:
train_df.shape, test_df.shape

((10000, 56), (5001, 56))

In [14]:
train_df.columns

Index(['P100', 'P101', 'P102', 'P103', 'P104', 'P105', 'P106', 'P107', 'P108',
       'P109', 'P111', 'P112', 'Q100', 'Q102', 'Q103', 'Q104', 'Q105', 'Q106',
       'Q107', 'Q108', 'Q109', 'Q111', 'P_flow_99_100', 'Q_flow_99_100',
       'P_flow_100_101', 'Q_flow_100_101', 'P_flow_99_102', 'Q_flow_99_102',
       'P_flow_99_103', 'Q_flow_99_103', 'P_flow_102_103', 'Q_flow_102_103',
       'P_flow_102_104', 'Q_flow_102_104', 'P_flow_99_105', 'Q_flow_99_105',
       'P_flow_103_104', 'Q_flow_103_104', 'P_flow_104_105', 'Q_flow_104_105',
       'P_flow_104_106', 'Q_flow_104_106', 'P_flow_104_107', 'Q_flow_104_107',
       'P_flow_105_106', 'Q_flow_105_106', 'P_flow_107_108', 'Q_flow_107_108',
       'P_flow_102_109', 'Q_flow_102_109', 'P_flow_108_109', 'Q_flow_108_109',
       'P_flow_109_110', 'Q_flow_109_110', 'P_flow_109_111', 'Q_flow_109_111'],
      dtype='object')

In [16]:
from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata

In [19]:
# Define metadata (schema) from your dataframe
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=df)

In [20]:
# Initialize synthesizer
synthesizer = CTGANSynthesizer(metadata, epochs=300,verbose=True)

C:\Users\digan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sdv\single_table\base.py:168: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
C:\Users\digan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

In [21]:
# Train
synthesizer.fit(train_df)

Gen. (-0.92) | Discrim. (-0.63): 100%|██████████| 300/300 [26:09<00:00,  5.23s/it]

In [36]:
synthesizer.save(
    filepath='CT_GAN_FOR_AC_FDIA.pkl'
)

In [27]:
synthesizer.get_loss_values()

     Epoch  Generator Loss  Discriminator Loss
0        0       -0.731618            0.243575
1        1       -0.574578            0.024102
2        2       -0.435078            0.201168
3        3       -0.316483            0.052835
4        4       -0.606307            0.112844
..     ...             ...                 ...
295    295       -1.682139            0.139913
296    296       -1.337652            0.008238
297    297       -1.262384           -0.120239
298    298       -1.529215            0.187190
299    299       -0.919706           -0.632634

[300 rows x 3 columns]

In [22]:
synthetic_df = synthesizer.sample(len(test_df))

In [24]:
test_df.head()

,P100,P101,P102,P103,P104,P105,P106,P107,P108,P109,...,P_flow_107_108,Q_flow_107_108,P_flow_102_109,Q_flow_102_109,P_flow_108_109,Q_flow_108_109,P_flow_109_110,Q_flow_109_110,P_flow_109_111,Q_flow_109_111
10000,153.765709,-34.983802,-39.226868,31.261699,35.407601,37.050139,-19.667740,0.012793,-43.270554,-7.451878,...,38.357286,-5.703097,29.361018,-7.784437,45.655726,-2.840706,68.089767,-18.812012,6.010234,-5.404341
10001,158.981691,-39.851423,-44.707141,38.524472,29.088478,35.695729,-23.895874,0.953100,-44.688572,-6.122640,...,47.812500,-8.488095,36.232173,-8.825413,53.694748,-4.967325,82.598838,-22.092131,6.010234,-5.404341
10002,146.177719,-49.793815,-49.961470,34.872560,27.784354,47.247876,-25.202423,0.793533,-44.460058,-5.423448,...,43.983519,-7.377259,34.278880,-8.538702,49.203897,-4.501300,75.331888,-20.471565,7.013934,-5.786200
10003,143.142052,-46.947511,-43.806639,44.143490,25.594726,49.745408,-21.423240,-0.354987,-40.973210,-7.161181,...,34.621365,-4.504001,25.996004,-7.241527,41.658306,-0.716194,61.901879,-17.358692,5.007105,-5.021854
10004,146.425610,-45.208361,-42.701340,34.445292,35.489793,35.462733,-25.015398,0.497516,-53.635303,-4.944572,...,48.708586,-7.271144,32.242937,-8.232078,53.406476,-3.588705,78.443246,-21.170882,6.010234,-5.404341

In [23]:
synthetic_df.head()

,P100,P101,P102,P103,P104,P105,P106,P107,P108,P109,...,P_flow_107_108,Q_flow_107_108,P_flow_102_109,Q_flow_102_109,P_flow_108_109,Q_flow_108_109,P_flow_109_110,Q_flow_109_110,P_flow_109_111,Q_flow_109_111
0,151.509941,-37.969756,-42.907212,30.768613,37.199479,47.896470,-19.638420,-0.163869,-47.319816,-7.469448,...,38.776487,-3.772201,24.412021,-7.371241,39.101824,0.524336,58.932008,-16.718056,4.982190,-5.410068
1,159.919614,-41.349024,-35.390900,32.008061,34.590300,47.917019,-21.319631,-0.978852,-42.766489,-7.558872,...,34.259313,-4.393034,27.099276,-8.074503,47.425878,-1.392429,71.655391,-17.565596,6.019403,-5.402293
2,123.802250,-50.124782,-44.629977,36.683091,26.148103,33.952030,-23.580008,0.667209,-59.019450,-8.198430,...,47.622636,-8.808035,28.199399,-8.659182,49.280265,-1.532346,82.598838,-20.438216,5.992354,-5.403820
3,140.572646,-49.474096,-38.345789,44.449134,29.700494,35.821837,-22.453781,0.268843,-44.480488,-5.454879,...,36.943888,-4.604620,28.790812,-8.793115,47.173918,-3.423552,79.048169,-18.439845,4.998000,-5.404862
4,153.732010,-34.034273,-41.605607,45.330775,36.838236,43.472786,-21.192202,-0.499903,-47.325414,-6.448932,...,40.896052,-5.913320,25.994019,-7.091087,47.551817,-1.851929,72.804815,-20.280645,5.009950,-5.411403

In [26]:
import pandas as pd

# Compare mean and std side by side
stats_df = pd.DataFrame({
    "Real_Mean": test_df.mean(),
    "Synthetic_Mean": synthetic_df.mean(),
    "Real_Std": test_df.std(),
    "Synthetic_Std": synthetic_df.std()
})

print(stats_df)

                 Real_Mean  Synthetic_Mean   Real_Std  Synthetic_Std
P100            141.879302      145.021074  13.794359      15.825828
P101            -42.103688      -42.104386   4.797251       4.747054
P102            -44.001336      -42.114084   3.723443       4.133603
P103             38.091667       37.470281   4.370431       4.157520
P104             30.983364       31.930861   3.611299       3.683909
P105             41.082615       40.313774   4.992351       5.286067
P106            -23.004348      -22.857220   2.640829       2.515648
P107              0.169346        0.271604   0.481454       0.520626
P108            -49.946239      -50.430783   5.759347       5.942063
P109             -6.167517       -6.514731   1.012016       1.075670
P111             67.813201       66.805500   7.880979       8.059248
P112              5.994988        5.988180   0.687829       0.761617
Q100             34.978678       36.926141   5.551337       6.780059
Q102             -2.421280       -2.243096   0.993575       1.111023
Q103             25.018129       25.017661   2.893004       2.772250
Q104             26.012482       24.777608   2.989014       2.905792
Q105             16.000179       15.693396   1.833002       1.905407
Q106            -15.998803      -16.570000   1.852042       1.753861
Q107              1.000807        0.986011   0.115052       0.121672
Q108            -11.996325      -12.388339   1.393540       1.374908
Q109             -2.999732       -2.927617   0.346325       0.351008
Q111             13.010033       12.799105   1.500572       1.491339
P_flow_99_100    -4.028838       -4.587736   4.070989       4.172899
Q_flow_99_100    -8.153777       -8.455374   0.568498       0.601791
P_flow_100_101   38.053921       37.846079   3.569472       4.028818
Q_flow_100_101   -4.938296       -5.142103   0.543641       0.598572
P_flow_99_102    72.076203       70.721615   8.021860       8.633901
Q_flow_99_102   -23.017377      -23.625012   2.087532       2.450616
P_flow_99_103    22.321127       22.322023   2.903764       3.547061
Q_flow_99_103    -7.076950       -7.272964   0.498143       0.555883
P_flow_102_103    3.734006        3.767052   1.458143       1.524821
Q_flow_102_103   -3.118525       -3.020870   0.418816       0.473626
P_flow_102_104    2.518250        2.369428   1.865339       2.205038
Q_flow_102_104   -2.859308       -3.035651   0.604708       0.621173
P_flow_99_105    11.686144       10.152672   2.620034       3.095161
Q_flow_99_105   -10.246894      -10.232639   0.626243       0.719739
P_flow_103_104   -4.672525       -3.830913   3.763950       3.791115
Q_flow_103_104    0.743485        0.751415   0.997219       1.223191
P_flow_104_105  -29.973919      -29.452122   2.542490       2.921502
Q_flow_104_105  -10.746349      -11.079027   1.356014       1.554783
P_flow_104_106   -4.497597       -4.570098   0.404647       0.450264
Q_flow_104_106   -1.035439       -1.062538   0.121111       0.140339
P_flow_104_107   -8.273480       -7.422185   5.739001       6.885521
Q_flow_104_107  -18.707274      -18.816505   1.601745       1.942674
P_flow_105_106    4.457633        4.535696   0.407503       0.432663
Q_flow_105_106    1.717375        1.559318   0.382764       0.374496
P_flow_107_108   41.563071       40.309088   4.303728       4.716226
Q_flow_107_108   -5.135137       -5.257467   1.477334       1.607257
P_flow_102_109   27.322101       26.812302   4.942674       5.443169
Q_flow_102_109   -7.434538       -7.768915   0.800177       0.822373
P_flow_108_109   47.550016       48.172138   4.220569       4.800683
Q_flow_108_109   -1.850438       -1.322369   1.561296       1.676099
P_flow_109_110   68.431761       69.925513   8.147029       8.696246
Q_flow_109_110  -18.863158      -18.902148   1.888888       1.974713
P_flow_109_111    5.509062        5.742142   0.758172       0.695791
Q_flow_109_111   -5.213111       -5.290571   0.289092       0.257093

In [29]:
from sdv.evaluation.single_table import run_diagnostic, evaluate_quality
from sdv.evaluation.single_table import get_column_plot

In [31]:
# 1. perform basic validity checks
diagnostic = run_diagnostic(test_df, synthetic_df, metadata)

# 2. measure the statistical similarity
quality_report = evaluate_quality(test_df, synthetic_df, metadata)

Generating report ...

(1/2) Evaluating Data Validity: |██████████| 56/56 [00:00<00:00, 2393.40it/s]|
Data Validity Score: 98.96%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<00:00, 498.91it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 99.48%

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 56/56 [00:00<00:00, 718.43it/s]|
Column Shapes Score: 90.02%

(2/2) Evaluating Column Pair Trends: |██████████| 1540/1540 [00:04<00:00, 353.44it/s]|
Column Pair Trends Score: 93.96%

Overall Score (Average): 91.99%

In [32]:
test_df.columns

Index(['P100', 'P101', 'P102', 'P103', 'P104', 'P105', 'P106', 'P107', 'P108',
       'P109', 'P111', 'P112', 'Q100', 'Q102', 'Q103', 'Q104', 'Q105', 'Q106',
       'Q107', 'Q108', 'Q109', 'Q111', 'P_flow_99_100', 'Q_flow_99_100',
       'P_flow_100_101', 'Q_flow_100_101', 'P_flow_99_102', 'Q_flow_99_102',
       'P_flow_99_103', 'Q_flow_99_103', 'P_flow_102_103', 'Q_flow_102_103',
       'P_flow_102_104', 'Q_flow_102_104', 'P_flow_99_105', 'Q_flow_99_105',
       'P_flow_103_104', 'Q_flow_103_104', 'P_flow_104_105', 'Q_flow_104_105',
       'P_flow_104_106', 'Q_flow_104_106', 'P_flow_104_107', 'Q_flow_104_107',
       'P_flow_105_106', 'Q_flow_105_106', 'P_flow_107_108', 'Q_flow_107_108',
       'P_flow_102_109', 'Q_flow_102_109', 'P_flow_108_109', 'Q_flow_108_109',
       'P_flow_109_110', 'Q_flow_109_110', 'P_flow_109_111', 'Q_flow_109_111'],
      dtype='object')

In [37]:
test_df.to_csv('test_data_only_PQ.csv', index=False)

In [38]:
synthetic_df.to_csv('synthetic_data_only_PQ.csv', index=False)